#!/usr/bin/env bash
# install nginx and return a page
sudo apt-get update;
sudo apt-get -y install nginx;
sudo service nginx start;
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
