#!/usr/bin/env bash
# redirection must be a "301 moved permanently"
apt-get update
apt-get -y install nginx
service nginx start
new_string="rewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
file="/etc/nginx/sites-available/default"
sed -i "26i $new_string" $file
service nginx restart && service nginx reload
