#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
apt-get update
apt-get -y install nginx
service nginx start
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
service nginx reload
service nginx restart

