#!/usr/bin/env bash
# install nginx
# listening on port 80
# returns a page containing string when sent a GET request at root
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo rm /usr/share/nginx/html/index.html
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
# redirection must be a "301 moved permanently"
new_string="rewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
file="/etc/nginx/sites-available/default"
sed -i "26i $new_string" $file
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
new_string_404='\     rewrite ^/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;location /xyz{ return 404;}error_page 404 /404.html;location = /404.html {root /usr/share/nginx/html;internal;}# Make site accessible from http://localhost/server_name localhost;'
sed -i "26i $new_string_404" $file
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
service nginx restart && service nginx reload

