#!/usr/bin/env bash
# shellcheck disable=SC2086
# Bash script that displays information about subdomains
prettifydig () {
    domain="$1"
    subdomain="$2"
    dig $subdomain $domain | grep -A1 ';; ANSWER SECTION:' | grep -v 'ANSWER' | awk -v awk_sub="$subdomain" '{printf "The subdomain %s is a %s record and points to %s\n", awk_sub, $4, $5}'
}

allsubdomains=("www" "lb-01" "web-01" "web-02")
if [ $# -eq 1 ];
then
    for a in "${allsubdomains[@]}"
    do
        prettifydig "$1"
    done
elif [ $# -eq 2 ];
then
    prettifyDig "$1" "$2"
fi
