#!/usr/bin/env bash
#shell script to configure a server to the following requirements
#Nginx must be running, and listening on port 80 of all the server's active IPv4 IPs
apt-get update
apt-get -y install nginx
service nginx start
