#!/usr/bin/env bash
# This script extends previous exercise command and displays line containing the bash word, this allowing you to easily get the PID of your Bash process
# You cannot use pgrep
./1-list_your_processes | grep "bash"
# shellcheck disable=SC2009
